name: Deploy Frontend

on:
  push:
    branches:
      - main # 你可以根据需要更改为适合的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 或你使用的其他 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build project
        run: |
          cd frontend
          pnpm build-only

      - name: Archive build result
        run: |
          cd frontend
          zip -r dist.zip dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: frontend_preview-${{ github.run_id }}
          release_name: Frontend Preview ${{ github.run_id }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: frontend/dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
