name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build project
        run: |
          cd frontend
          pnpm build

      - name: Create Release
        id: create_release
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          gh release create frontend_preview-${VERSION} frontend/dist/** --title "Frontend Preview ${VERSION}" --notes "Automated release for frontend preview."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist
